### ISSUE TITLE
OE Improvements for Site

### ISSUE THREAD

**Issue by jachan** [newjersey/taxation-mef-viewer#3]
These tasks will allow development to occur on this software package.

```[tasklist]
### Tasks
- [ ] Automatic Testing through Github Actions on PR
- [ ] Markdown Template for PRs in Github folder
- [ ] Ruby Upgrade to 3.x?
- [x] Nokogiri must be downgraded to 1.12.4 while dependency issues with 1.16.x are resolved
```
